name:                 circuits-io
version:              0.1.0.0
visibility:           public
id:                   circuits-io-0.1.0.0-inplace
key:                  circuits-io-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            Tony Day (c) 2025
maintainer:           tonyday567@gmail.com
author:               Tony Day
homepage:             https://github.com/tonyday567/circuits#readme
synopsis:
    IO combinators for the circuits library — fileIO, socket, server, timing, async

description:
    @circuits-io@ provides batteries-included IO combinators for the circuits library,
    including file I/O, IORef, socket, server, timing, and async operations.
    Built on Circuit.Channel's Producer/Consumer framework.

category:             control
abi:                  inplace
exposed:              True
exposed-modules:
    Circuit.Channel Circuit.IO Circuit.IO.File Circuit.IO.Queue
    Circuit.IO.Repl Circuit.IO.Socket.Types Circuit.IO.TCP
    Circuit.IO.TCP.Example Circuit.IO.Time Circuit.IO.Websocket
    Circuit.IO.Websocket.Example

import-dirs:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/build

data-dir:             /Users/tonyday567/haskell/circuits-io/.
hs-libraries:         HScircuits-io-0.1.0.0-inplace
depends:
    sync-2.2.6-fb1c8d9c base-4.22.0.0-1f90 bx-0.9.4.0-25fdebfa
    bytestring-0.12.2.0-5637 circuits-0.1.0.0-inplace
    containers-0.8-034d drctry-1.3.10.1-b685f8e7
    ntwrk-smpl-0.4.5-b0e56f01 prcss-1.6.28.0-a73298e3
    prfnctrs-5.6.3-00f42c3b stm-2.5.3.1-8fc0 tmprry-1.3-f3636789
    text-2.1.3-a2fa tm-1.14-0dce814b wbsckts-0.13.0.0-05eac2be

haddock-interfaces:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/doc/html/circuits-io/circuits-io.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-io/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-io-0.1.0.0/doc/html/circuits-io
